// checksum 0xfde6 version 0x90005
/*
  This file was generated by the Qt Quick 2 Application wizard of Qt Creator.
  QtQuick2ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QTQUICK2APPLICATIONVIEWER_H
#define QTQUICK2APPLICATIONVIEWER_H

#include <QtQuick/QQuickView>
#include "IQtQuick2ApplicationViewer.h"

class QtQuick2ApplicationViewer : public QQuickView,
                                  virtual public Pangim::IQtQuick2ApplicationViewer
{
    Q_OBJECT
    Q_INTERFACES(Pangim::IQtQuick2ApplicationViewer)

public:
    explicit QtQuick2ApplicationViewer(QWindow *parent = 0);
    virtual ~QtQuick2ApplicationViewer();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);

    void showExpanded();

    Q_SIGNAL void closingQmlApplicationViewer();

    //Pangim::IQtQuick2ApplicationViewer Implementation
    QObject* containerObject();
    QObject* findObject(const QString &objectName);

protected:
    bool event(QEvent *event);

private:
    class QtQuick2ApplicationViewerPrivate *d;
};

#endif // QTQUICK2APPLICATIONVIEWER_H
